name: dellyshop
description: Delly Shop e-commerce app for flutter

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  flutter_html: ^2.2.0
  random_pk: any
  shimmer: ^2.0.0
  transparent_image: ^2.0.0
  flutter_slidable: ^1.3.0
  flutter_rating: ^0.0.2
  carousel_slider : ^4.1.1
  jiffy : any
  uuid : ^3.0.6
  flutter_local_notifications: ^8.2.0
  hive: ^2.2.1
  firebase_core: ^1.2.1
  firebase_messaging: ^11.4.0
  intro_views_flutter: ^3.2.0
  geocoding:
  shared_preferences: ^2.0.15
  rxdart:
  toast: ^0.3.0
  get_it: ^7.2.0
  connectivity:
  scroll_to_index: ^3.0.1
  multi_select_flutter: ^4.1.2
  flutter_datetime_picker: ^1.5.1
  bubble: ^1.1.9+1
  # dash_chat:
  flutter_bloc: ^8.0.1
  contacts_service: ^0.6.3
  permission_handler: ^9.2.0
  built_value: ^8.3.2
  analyzer: ^4.1.0
  flutter_spinkit: ^5.1.0
  flutter_screenutil: ^5.5.3+1
  url_launcher:
  device_simulator: ^0.9.6
  sqflite:
  path_provider:
  intl: ^0.17.0
  sms_autofill: ^2.2.0
  country_picker:
  image_picker: ^0.8.1+1
  email_validator: ^2.0.1
  rating_dialog: ^2.0.4
  page_transition: ^2.0.5
  flutter_country_picker: ^0.1.6
  dartz: ^0.10.1
  # either_option: ^1.0.5
  regexpattern: ^2.0.1
  flutter_rounded_date_picker: ^2.0.2
  awesome_dialog: ^2.2.1
  flutter_svg:
  dropdown_search: ^4.0.1
  flutter_verification_code: ^1.1.3
  font_awesome_flutter: ^10.1.0
  # flutter_map: ^0.10.1+1
  flutter_rating_bar: ^4.0.1
  flutter_swiper: ^1.1.6
  flutter_tags: ^0.4.9+1
  http: ^0.13.2
  fluttertoast: ^8.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lang/

  fonts:
    - family: Popins
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 700